# Generated by Django 3.2.1 on 2021-05-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='TotalAmount',
            field=models.IntegerField(),
        ),
    ]
