# Generated by Django 3.2.1 on 2021-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_countrymodel_totalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='TotalAmount',
            new_name='NetAmount',
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='Tax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
