# Generated by Django 3.2.1 on 2021-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210531_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRegionCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Orders', models.IntegerField()),
                ('Income', models.IntegerField()),
            ],
        ),
    ]
