# Generated by Django 3.2.1 on 2021-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20210603_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescountrymonthmodel',
            name='NetAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salescountrymonthmodel',
            name='Tax',
            field=models.IntegerField(null=True),
        ),
    ]
