# Generated by Django 3.2.1 on 2021-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210603_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescountrymonthmodel',
            name='NetAmount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='salescountrymonthmodel',
            name='Tax',
            field=models.IntegerField(default=1000),
        ),
    ]
