# Generated by Django 3.2.1 on 2021-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('FullName', models.CharField(max_length=101)),
                ('Age', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateID', models.IntegerField()),
                ('Date', models.DateField()),
                ('Day', models.IntegerField()),
                ('Month', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Weekday', models.CharField(max_length=50)),
                ('WeekInYear', models.IntegerField()),
                ('WeekInMonth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationID', models.IntegerField()),
                ('Region', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderlineID', models.IntegerField()),
                ('Order', models.IntegerField()),
                ('Location', models.IntegerField()),
                ('Product', models.IntegerField()),
                ('Customer', models.IntegerField()),
                ('Date', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('NetAmount', models.FloatField()),
                ('Tax', models.FloatField()),
                ('TotalAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Actor', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Special', models.CharField(max_length=5)),
            ],
        ),
    ]
